import {describe,it,expect} from 'vitest';
import {derive,append,undoLastBall,correctBall} from '../src/lib/scoring/engine';
import {defaultMatch,type Match,type Ball,overs,rate} from '../src/lib/scoring/model';
let serial=0;
const stamp=()=>({id:`e${++serial}`,at:'2026-10-02T06:00:00Z'});
const ball=(bat=0,extra:Ball['extra']='none',extraRuns=0,rest:Partial<Ball>={}):Ball=>({kind:'ball',...stamp(),bat,extra,extraRuns,...rest});
const start=():Match=>append(defaultMatch(),{kind:'start',...stamp(),striker:'blue-1',nonStriker:'blue-2',bowler:'red-1'});
const event=(m:Match,kind:'end'|'finish'|'super')=>append(m,{kind,...stamp()});
function next(m:Match,bat=0):Match{const i=derive(m).current!;if(i.needsBowler)m=append(m,{kind:'players',...stamp(),striker:i.striker,nonStriker:i.nonStriker,bowler:i.bowler==='red-1'?'red-2':i.bowler==='blue-1'?'blue-2':i.fielding==='red'?'red-1':'blue-1'});return append(m,ball(bat));}
function chase(runs:number,oversCount=20){let m=defaultMatch();m.config.overs=oversCount;m=append(m,{kind:'start',...stamp(),striker:'blue-1',nonStriker:'blue-2',bowler:'red-1'});if(runs)m=append(m,ball(runs));m=event(m,'end');return append(m,{kind:'start',...stamp(),striker:'red-1',nonStriker:'red-2',bowler:'blue-1'});}
describe('runs, strike and overs',()=>{
 it.each([0,1,2,3,4,6])('scores %i runs',runs=>{const i=derive(append(start(),ball(runs))).current!;expect(i.runs).toBe(runs);expect(i.balls).toBe(1);expect(i.batters['blue-1']).toMatchObject({runs,balls:1,fours:runs===4?1:0,sixes:runs===6?1:0});expect(i.bowlers['red-1'].runs).toBe(runs);expect(i.striker).toBe(runs%2?'blue-2':'blue-1');expect(i.partnership).toEqual({runs,balls:1});});
 it('swaps ends after six legal deliveries',()=>{let m=start();for(let j=0;j<6;j++)m=next(m);const i=derive(m).current!;expect(overs(i.balls)).toBe('1.0');expect(i.striker).toBe('blue-2');expect(i.needsBowler).toBe(true);expect(i.bowlers['red-1'].maidens).toBe(1);expect(()=>append(m,ball())).toThrow('next bowler');expect(()=>append(m,{kind:'players',...stamp(),striker:i.striker,nonStriker:i.nonStriker,bowler:'red-1'})).toThrow('different bowler');});
 it('swaps twice for an odd sixth ball',()=>{let m=start();for(let j=0;j<5;j++)m=next(m);m=next(m,1);expect(derive(m).current!.striker).toBe('blue-1');});
 it('never treats overs as decimals',()=>{expect(overs(7)).toBe('1.1');expect(rate(12,7)).toBe('10.29');});
 it('tracks run fours without a boundary',()=>{expect(derive(append(start(),ball(4,'none',0,{boundary:false}))).current!.batters['blue-1'].fours).toBe(0);});
});
describe('extras',()=>{
 it.each([1,2,3,4,5])('%i wides are not legal balls or balls faced',n=>{const i=derive(append(start(),ball(0,'wide',n))).current!;expect(i.runs).toBe(n);expect(i.balls).toBe(0);expect(i.batters['blue-1'].balls).toBe(0);expect(i.bowlers['red-1'].runs).toBe(n);expect(i.extras.wide).toBe(n);expect(i.striker).toBe((n-1)%2?'blue-2':'blue-1');});
 it('no-ball only counts a ball faced but not a legal delivery',()=>{const i=derive(append(start(),ball(0,'no-ball',1))).current!;expect(i.runs).toBe(1);expect(i.balls).toBe(0);expect(i.batters['blue-1'].balls).toBe(1);expect(i.freeHit).toBe(true);});
 it('no-ball + four separates penalty from bat runs',()=>{const i=derive(append(start(),ball(4,'no-ball',1,{noBallAdditional:'bat'}))).current!;expect(i.runs).toBe(5);expect(i.batters['blue-1'].runs).toBe(4);expect(i.bowlers['red-1'].runs).toBe(5);expect(i.extras.noBall).toBe(1);});
 it.each(['bye','leg-bye'] as const)('no-ball + %s charges only the penalty to bowler',extra=>{const i=derive(append(start(),ball(0,'no-ball',4,{noBallAdditional:extra}))).current!;expect(i.runs).toBe(4);expect(i.bowlers['red-1'].runs).toBe(1);expect(i.batters['blue-1'].runs).toBe(0);expect(i.striker).toBe('blue-2');expect(i.extras[extra==='bye'?'bye':'legBye']).toBe(3);});
 it.each(['bye','leg-bye'] as const)('%s adds team runs but no bowler runs',extra=>{const i=derive(append(start(),ball(0,extra,3))).current!;expect(i.runs).toBe(3);expect(i.balls).toBe(1);expect(i.batters['blue-1'].balls).toBe(1);expect(i.bowlers['red-1'].runs).toBe(0);expect(i.striker).toBe('blue-2');});
 it('wide and no-ball preserve a free hit until legal delivery',()=>{let m=append(start(),ball(0,'no-ball',1));m=append(m,ball(0,'wide',1));expect(derive(m).current!.freeHit).toBe(true);m=append(m,ball());expect(derive(m).current!.freeHit).toBe(false);});
 it('rejects invalid combinations',()=>{expect(()=>append(start(),ball(4,'wide',1))).toThrow();expect(()=>append(start(),ball(0,'no-ball',3))).toThrow();expect(()=>append(start(),ball(0,'none',1))).toThrow();});
});
describe('dismissals and retirements',()=>{
 it.each(['Bowled','Caught','LBW','Stumped','Hit wicket'] as const)('%s credits the bowler',how=>{const i=derive(append(start(),ball(0,'none',0,{wicket:{how,player:'blue-1',incoming:'blue-3'}}))).current!;expect(i.wickets).toBe(1);expect(i.bowlers['red-1'].wickets).toBe(1);expect(i.batters['blue-1'].status).toBe(how);expect(i.striker).toBe('blue-3');});
 it.each(['Run out','Other'] as const)('%s does not credit the bowler',how=>{const i=derive(append(start(),ball(0,'none',0,{wicket:{how,player:'blue-1',incoming:'blue-3'}}))).current!;expect(i.wickets).toBe(1);expect(i.bowlers['red-1'].wickets).toBe(0);});
 it('run-out + completed runs swaps before replacement',()=>{const i=derive(append(start(),ball(1,'none',0,{wicket:{how:'Run out',player:'blue-2',incoming:'blue-3'}}))).current!;expect(i.runs).toBe(1);expect(i.striker).toBe('blue-3');expect(i.nonStriker).toBe('blue-1');expect(i.batters['blue-1'].runs).toBe(1);expect(i.partnership.runs).toBe(0);});
 it('allows umpire end correction on run-out',()=>{const i=derive(append(start(),ball(0,'none',0,{wicket:{how:'Run out',player:'blue-1',incoming:'blue-3',nextStriker:'blue-2'}}))).current!;expect(i.striker).toBe('blue-2');});
 it('allows stumping on a wide',()=>{const i=derive(append(start(),ball(0,'wide',1,{wicket:{how:'Stumped',player:'blue-1',incoming:'blue-3'}}))).current!;expect(i.balls).toBe(0);expect(i.runs).toBe(1);expect(i.wickets).toBe(1);});
 it('rejects caught on no-ball and bowled on free hit',()=>{expect(()=>append(start(),ball(0,'no-ball',1,{wicket:{how:'Caught',player:'blue-1',incoming:'blue-3'}}))).toThrow();const m=append(start(),ball(0,'no-ball',1));expect(()=>append(m,ball(0,'none',0,{wicket:{how:'Bowled',player:'blue-1',incoming:'blue-3'}}))).toThrow('free hit');});
 it('supports retired hurt returning later without a wicket',()=>{let m=append(start(),{kind:'retire',...stamp(),player:'blue-1',incoming:'blue-3',out:false});let i=derive(m).current!;expect(i.wickets).toBe(0);expect(i.batters['blue-1'].status).toBe('Retired hurt');m=append(m,ball(0,'none',0,{wicket:{how:'Bowled',player:'blue-3',incoming:'blue-1'}}));i=derive(m).current!;expect(i.striker).toBe('blue-1');expect(i.batters['blue-1'].status).toBe('Not out');});
 it('retired out is a team wicket only',()=>{const i=derive(append(start(),{kind:'retire',...stamp(),player:'blue-1',incoming:'blue-3',out:true})).current!;expect(i.wickets).toBe(1);expect(i.balls).toBe(0);expect(i.bowlers['red-1'].wickets).toBe(0);});
});
describe('undo and corrections',()=>{
 it.each([ball(4),ball(0,'wide',1),ball(2,'no-ball',1),ball(0,'none',0,{wicket:{how:'Bowled',player:'blue-1',incoming:'blue-3'}})])('undo restores the entire pre-ball state',b=>{const m=start();expect(derive(undoLastBall(append(m,b)))).toEqual(derive(m));});
 it('undo removes dependent over and innings transitions',()=>{let m=append(start(),ball(4));m=event(m,'end');m=append(m,{kind:'start',...stamp(),striker:'red-1',nonStriker:'red-2',bowler:'blue-1'});expect(derive(undoLastBall(m)).innings).toHaveLength(1);expect(derive(undoLastBall(m)).current!.runs).toBe(0);});
 it('edits an old delivery and recalculates later batter attribution',()=>{const first=ball(1);let m=append(start(),first);m=append(m,ball(4));m=correctBall(m,first.id,{...first,bat:2});const i=derive(m).current!;expect(i.runs).toBe(6);expect(i.batters['blue-1'].runs).toBe(6);expect(i.batters['blue-2'].runs).toBe(0);});
 it('rejects corrections that invalidate a later innings',()=>{let m=chase(4);m=append(m,ball(4));m=event(m,'end');m=event(m,'finish');const second=derive(m).current!.deliveries[0].event;expect(()=>correctBall(m,second.id,{...second,bat:6})).toThrow();});
 it('rejects duplicate event IDs',()=>{const b=ball();expect(()=>append(append(start(),b),b)).toThrow('Duplicate');});
});
describe('innings, results and Super Overs',()=>{
 it('ends at 20 overs / 120 legal balls',()=>{let m=start();for(let n=0;n<120;n++)m=next(m);const s=derive(m);expect(s.status).toBe('INNINGS_BREAK');expect(s.current!.balls).toBe(120);expect(s.current!.ended).toBe(true);});
 it('creates target from the first innings',()=>{const i=derive(chase(6)).current!;expect(i.target).toBe(7);});
 it('successful chase waits for finish confirmation',()=>{let m=append(chase(3),ball(4));expect(derive(m).status).toBe('AWAITING_FINISH');expect(derive(m).result).toBe('Red House won by 10 wickets');m=event(m,'finish');expect(derive(m).status).toBe('COMPLETED');expect(()=>append(m,ball())).toThrow('Completed');});
 it('defending side wins by runs',()=>{let m=chase(6,1);for(let n=0;n<6;n++)m=next(m);expect(derive(m).result).toBe('Blue House won by 6 runs');});
 it('ends all out without asking for an 11th replacement',()=>{let m=start();for(let n=0;n<10;n++){const i=derive(m).current!;if(i.needsBowler)m=append(m,{kind:'players',...stamp(),striker:i.striker,nonStriker:i.nonStriker,bowler:'red-2'});m=append(m,ball(0,'none',0,{wicket:{how:'Bowled',player:i.striker,incoming:n<9?`blue-${n+3}`:undefined}}));}expect(derive(m).status).toBe('INNINGS_BREAK');expect(derive(m).current!.wickets).toBe(10);});
 it('ties may be finalized',()=>{let m=chase(0,1);for(let n=0;n<6;n++)m=next(m);expect(derive(m).status).toBe('TIED');expect(derive(event(m,'finish')).result).toBe('Match tied');});
 it('stores Super Overs separately with 6-ball and 2-wicket limits',()=>{let m=event(chase(0),'end');m=event(m,'super');expect(derive(m).superPending).toBe(true);m=append(m,{kind:'start',...stamp(),striker:'red-1',nonStriker:'red-2',bowler:'blue-1'});for(let n=0;n<6;n++)m=next(m,n===0?1:0);expect(derive(m).status).toBe('INNINGS_BREAK');m=append(m,{kind:'start',...stamp(),striker:'blue-1',nonStriker:'blue-2',bowler:'red-1'});m=append(m,ball(2));const s=derive(m);expect(s.innings).toHaveLength(4);expect(s.current!.limit).toBe(6);expect(s.current!.wicketLimit).toBe(2);expect(s.result).toBe('Blue House won by 2 wickets in the Super Over');});
 it('Super Over ends after two wickets',()=>{let m=event(event(chase(0),'end'),'super');m=append(m,{kind:'start',...stamp(),striker:'red-1',nonStriker:'red-2',bowler:'blue-1'});m=append(m,ball(0,'none',0,{wicket:{how:'Bowled',player:'red-1',incoming:'red-3'}}));m=append(m,ball(0,'none',0,{wicket:{how:'Caught',player:'red-3'}}));expect(derive(m).status).toBe('INNINGS_BREAK');});
});
