'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowLeftRight,ArrowUpRight,Check,ChevronRight,Ellipsis,History,Play,RotateCcw,ShieldCheck,Trophy} from 'lucide-react';
import {AdminGate,Modal,SaveFeedback} from './admin-common';
import {useMatch} from './match-provider';
import {Loading} from './shell';
import {BallDots,BattingTable,BowlingTable,Crest,Scorecards,Squads} from './live-dashboard';
import {MatchTabs} from './match-ui';
import {append,correctBall,derive,undoLastBall} from '@/lib/scoring/engine';
import {type Ball,type Config,type Innings,type MatchEvent,type Team,dismissalSchema,overs,playerName,rate} from '@/lib/scoring/model';
const stamp=()=>({id:crypto.randomUUID(),at:new Date().toISOString()});
type Dialog='start'|'more'|'wicket'|'no-ball'|'extras'|'leg-bye'|'wide'|'players'|'retire'|'history'|null;
export function AdminPage(){return <AdminGate><Scorer/></AdminGate>;}
function Scorer(){
 const {record,save,busy,pending}=useMatch(),[dialog,setDialog]=useState<Dialog>(null),[edit,setEdit]=useState<Ball|null>(null),[localError,setLocalError]=useState(''),[view,setView]=useState('Scoring'),[scorecardInnings,setScorecardInnings]=useState<number|null>(null);
 if(!record)return <Loading/>;
 const m=record.data,c=m.config,s=derive(m),i=s.current,team=(id:string)=>c.teams.find(t=>t.id===id)!;
 const disabled=busy||pending;const active=!!i&&!i.ended&&s.status!=='COMPLETED';
 const commit=async(e:MatchEvent,msg:string)=>{setLocalError('');try{const ok=await save(append(m,e),msg);if(ok)setDialog(null);return ok;}catch(e){setLocalError(e instanceof Error?e.message:'Unable to record');return false;}};
 const ball=(runs:number)=>void commit({kind:'ball',...stamp(),bat:runs,extra:'none',extraRuns:0},`${runs===0?'Dot ball':runs===4?'FOUR':runs===6?'SIX':`${runs} run${runs===1?'':'s'}`} recorded ✓`);
 const automaticBowler=active&&i.needsBowler;
 const undo=async()=>{if(!confirm('Undo the last ball? Any bowler selection or innings transition after it will also be undone.'))return;try{await save(undoLastBall(m),'Last ball undone ✓');}catch(e){setLocalError((e as Error).message);}};
 return <div className="page scorer-page"><div className="scorer-heading"><div><h1>Scorer<span className="title-dot">.</span></h1><p>{c.title}</p></div><Link href="/live" className="text-button">Live view <ArrowUpRight size={16}/></Link></div><div className="scorer-workspace"><MatchTabs items={['Scoring','Scorecard','Players','Settings']} value={view} onChange={setView} label="Scorer views"/>
 {view==='Scorecard'&&<div className="tab-panel" role="tabpanel" aria-label="Scorecard"><div className="innings-tabs">{s.innings.map((inn,n)=><button key={n} className={(scorecardInnings??s.innings.length-1)===n?'selected':''} aria-pressed={(scorecardInnings??s.innings.length-1)===n} onClick={()=>setScorecardInnings(n)}>{team(inn.team).name}{inn.superOver?' · Super Over':''}</button>)}</div>{s.innings[scorecardInnings??s.innings.length-1]?<Scorecards innings={s.innings[scorecardInnings??s.innings.length-1]} config={c}/>:<div className="empty-state"><Trophy/><p>The scorecard appears when the innings begins.</p></div>}</div>}
 {view==='Players'&&<div className="tab-panel" role="tabpanel" aria-label="Players"><Squads config={c}/></div>}
 {view==='Settings'&&<div className="card innings-state tab-panel" role="tabpanel" aria-label="Settings"><ShieldCheck size={30}/><h2>Match controls</h2><p>Manage teams and match details, or review scoring corrections.</p><Link href="/setup" className="button primary">Edit match setup <ArrowUpRight size={16}/></Link><button className="button secondary" disabled={disabled} onClick={()=>setDialog('more')}>Corrections & match controls</button></div>}
 <div hidden={view!=='Scoring'} role="tabpanel" aria-label="Scoring"><div className="scorer-score"><Crest team={team(i?.team??s.nextTeam)}/><div><span className="eyebrow">{team(i?.team??s.nextTeam).name} {i?.superOver?'· SUPER OVER':''}</span><strong key={`${i?.index}-${i?.runs}-${i?.wickets}`}>{i?.runs??0}<span>/{i?.wickets??0}</span></strong><p className="score-overs">{i?overs(i.balls):'0.0'} / {i?.superOver?1:c.overs} overs</p></div><div className="scorer-over"><span>Run Rate</span><b>{i?rate(i.runs,i.balls):'0.00'}</b></div></div>{i?.target&&<div className="chase-strip">Target {i.target} <b>Need {Math.max(0,i.target-i.runs)} from {Math.max(0,i.limit-i.balls)} balls</b></div>}<SaveFeedback/>{localError&&<div className="error-banner" role="alert">{localError}<button className="text-button" onClick={()=>setLocalError('')}>Dismiss</button></div>}
 {active&&<><div className="card scorer-batters"><div className="card-heading"><h3>Batters</h3></div><BattingTable innings={i} config={c} activeOnly/></div><div className="card scorer-bowling"><div className="card-heading"><h3>Bowler</h3></div><BowlingTable innings={i} config={c} activeOnly/></div>{i.freeHit&&<div className="free-hit">FREE HIT · Usually only a run-out can dismiss a batter</div>}<div className="scoring-label"><h2>Runs off the bat</h2><span>One tap. Ball recorded.</span></div><div className="run-buttons">{[0,1,2,3,4,6].map(n=><button key={n} disabled={disabled||automaticBowler} className={n===6?'boundary-button six-button':n===4?'boundary-button':''} onClick={()=>ball(n)}><b>{n}</b><small>{n===0?'DOT BALL':n===4?'FOUR':n===6?'SIX':n===1?'RUN':'RUNS'}</small></button>)}</div><div className="special-buttons"><button className="extra-penalty" disabled={disabled||automaticBowler} onClick={()=>void commit({kind:'ball',...stamp(),bat:0,extra:'wide',extraRuns:1},'Wide recorded ✓')}>Wide</button><button className="extra-penalty" disabled={disabled||automaticBowler} onClick={()=>setDialog('no-ball')}>No Ball</button><button disabled={disabled||automaticBowler} onClick={()=>setDialog('extras')}>Bye</button><button disabled={disabled||automaticBowler} onClick={()=>setDialog('leg-bye')}>Leg Bye</button><button className="wicket-button" disabled={disabled||automaticBowler} onClick={()=>setDialog('wicket')}><span className="wicket-stumps" aria-hidden="true">Ⅲ</span> Wicket</button></div><div className="secondary-score-actions"><button disabled={disabled||!m.events.some(e=>e.kind==='ball')} onClick={()=>void undo()}><RotateCcw size={18}/> Undo last ball</button><button disabled={disabled} onClick={()=>setDialog('more')}><Ellipsis size={20}/> More</button></div><div className="recent-strip card"><span className="eyebrow">LAST SIX DELIVERIES</span><BallDots innings={i}/></div><p className="scorer-help"><Check size={15}/> Strike, overs and totals are handled for you.</p></>}
 {!active&&<div className="card innings-state"><Trophy size={35}/><h2>{s.status==='READY'?'Ready for the first ball?':s.status==='INNINGS_BREAK'?'Time for a change of innings':s.status==='COMPLETED'?'That’s a wrap!':s.superPending?'Super Over. Big moment.':s.result||'Innings complete'}</h2><p>{s.status==='READY'?'Choose the opening batters and bowler, then start scoring.':s.status==='INNINGS_BREAK'?`${team(s.nextTeam).name} need ${(i?.runs??0)+1} to win.`:s.status==='COMPLETED'?s.result:'Check the score before confirming the next step.'}</p>{(s.status==='READY'||s.status==='INNINGS_BREAK'||s.superPending)&&<button disabled={disabled} className="button primary" onClick={()=>setDialog('start')}><Play size={17}/>{s.status==='READY'?'Choose opening players':'Start next innings'}</button>}{(s.status==='TIED'||s.status==='AWAITING_FINISH')&&<div className="button-row"><button disabled={disabled} className="button primary" onClick={()=>{if(confirm(`Finish match: ${s.result}?`))void commit({kind:'finish',...stamp()},'Match completed ✓');}}>{s.status==='TIED'?'End as tie':'Finish match'}</button>{s.status==='TIED'&&<button disabled={disabled} className="button secondary" onClick={()=>{if(confirm('Start a Super Over? Each team gets 6 legal balls and 2 wickets.'))void commit({kind:'super',...stamp()},'Super Over selected ✓');}}>Start Super Over</button>}</div>}{i&&<button className="text-button" disabled={disabled} onClick={()=>setDialog('more')}>Corrections & match controls <ChevronRight size={15}/></button>}</div>}
 </div>
 {(dialog==='start')&&<PlayerDialog title="Choose opening players" config={c} team={team(s.nextTeam)} fielding={c.teams.find(t=>t.id!==s.nextTeam)!} busy={disabled} onClose={()=>setDialog(null)} onSubmit={(striker,nonStriker,bowler)=>{if(confirm('Start this innings with the selected players?'))void commit({kind:'start',...stamp(),striker,nonStriker,bowler},'Innings started ✓');}}/>}
 {(automaticBowler&&dialog===null)&&<Modal title="Select the next bowler" onClose={()=>setDialog('more')}><p className="muted">Over complete. Strike has already changed.</p><div className="player-options">{team(i.fielding).players.filter(p=>p.id!==i.previousBowler).map(p=><button disabled={disabled} className="button secondary" key={p.id} onClick={()=>void commit({kind:'players',...stamp(),striker:i.striker,nonStriker:i.nonStriker,bowler:p.id},`${p.name} to bowl ✓`)}>{p.name}</button>)}</div></Modal>}
 {dialog==='more'&&<Modal title="A little more control" onClose={()=>setDialog(null)}><div className="more-menu">{active&&<><button disabled={disabled} onClick={()=>void commit({kind:'players',...stamp(),striker:i.nonStriker,nonStriker:i.striker,bowler:i.bowler},'Strike swapped ✓')}><ArrowLeftRight/> Swap strike</button><button onClick={()=>setDialog('players')}>Correct current players / bowler</button><button onClick={()=>setDialog('wide')}>Multiple wides</button><button onClick={()=>setDialog('retire')}>Retired hurt / retired out</button></>}<button onClick={()=>setDialog('history')}><History/> Recent deliveries / corrections</button><button disabled={disabled||!m.events.some(e=>e.kind==='ball')} onClick={()=>{setDialog(null);void undo();}}><RotateCcw/> Undo last ball</button><button disabled={disabled||!m.events.length} onClick={()=>{if(confirm('Undo the most recent action, including an innings start, retirement or match completion?'))void save({...m,events:m.events.slice(0,-1)},'Last action undone ✓').then(ok=>{if(ok)setDialog(null);});}}>Undo last action / reopen result</button>{active&&<button className="danger-text" disabled={disabled} onClick={()=>{if(confirm('End this innings now? No further balls can be scored in this innings unless you undo this action.'))void commit({kind:'end',...stamp()},'Innings ended ✓');}}>End innings early</button>}<Link href="/setup">Edit match setup</Link><button className="danger-text" disabled={disabled} onClick={()=>{if(prompt('This clears every delivery. Type RESET to confirm.')==='RESET')void save({...m,events:[]},'Match reset ✓').then(ok=>{if(ok)setDialog(null);});}}>Reset match for practice</button></div></Modal>}
 {dialog==='players'&&i&&<PlayerDialog title="Correct players" config={c} team={team(i.team)} fielding={team(i.fielding)} innings={i} busy={disabled} onClose={()=>setDialog(null)} onSubmit={(striker,nonStriker,bowler)=>{if(confirm('Apply this player correction?'))void commit({kind:'players',...stamp(),striker,nonStriker,bowler},'Players corrected ✓');}}/>}
 {dialog==='retire'&&i&&<RetireDialog config={c} innings={i} busy={disabled} onClose={()=>setDialog(null)} onSubmit={(player,incoming,out)=>void commit({kind:'retire',...stamp(),player,incoming:incoming||undefined,out},out?'Retired out recorded ✓':'Retired hurt recorded ✓')}/>}
 {(['wicket','wide','no-ball','extras','leg-bye'].includes(dialog??'')||edit)&&i&&<DeliveryDialog key={edit?.id??dialog} config={c} innings={edit?derive({...m,events:m.events.slice(0,m.events.findIndex(e=>e.id===edit.id))}).current!:i} mode={edit?'edit':dialog!} initial={edit??undefined} busy={disabled} onClose={()=>{setDialog(null);setEdit(null);}} onSubmit={async b=>{if(edit){if(!confirm('Recalculate the innings using this corrected delivery? Later strike and batter statistics may change.'))return false;try{const ok=await save(correctBall(m,edit.id,b),'Delivery corrected ✓');if(ok)setEdit(null);return ok;}catch(e){setLocalError((e as Error).message);return false;}}return commit(b,'Delivery recorded ✓');}}/>}
 {dialog==='history'&&<Modal title="Recent deliveries / corrections" onClose={()=>setDialog(null)}><p className="muted">Choose a ball to correct. Totals and strike will be recalculated. Undo match completion before changing a final result.</p><div className="history-list">{s.innings.slice().reverse().map(inn=><div key={inn.index}><h3>{team(inn.team).name}{inn.superOver?' · Super Over':''}</h3>{inn.deliveries.slice().reverse().map(d=><button disabled={disabled||s.status==='COMPLETED'} key={d.event.id} onClick={()=>{setEdit(d.event);setDialog(null);}}><b>{d.label}</b><span>{d.text}</span><ChevronRight size={15}/></button>)}</div>)}</div></Modal>}
 </div></div>;
}
function PlayerSelect({label,value,onChange,players}:{label:string;value:string;onChange:(v:string)=>void;players:{id:string;name:string}[]}){return <label>{label}<select required value={value} onChange={e=>onChange(e.target.value)}><option value="">Choose a player</option>{players.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>;}
function PlayerDialog({title,team,fielding,innings,busy,onClose,onSubmit}:{title:string;config:Config;team:Team;fielding:Team;innings?:Innings;busy:boolean;onClose:()=>void;onSubmit:(s:string,n:string,b:string)=>void}){
 const [striker,setStriker]=useState(innings?.striker??team.players[0].id),[nonStriker,setNonStriker]=useState(innings?.nonStriker??team.players[1].id),[bowler,setBowler]=useState(innings?.bowler??fielding.players[0].id);
 const players=innings?team.players.filter(p=>[innings.striker,innings.nonStriker].includes(p.id)):team.players;
 return <Modal title={title} onClose={onClose}><form className="dialog-form" onSubmit={e=>{e.preventDefault();onSubmit(striker,nonStriker,bowler);}}><PlayerSelect label="Striker · facing the next ball" value={striker} onChange={setStriker} players={players}/><PlayerSelect label="Non-striker · at the other end" value={nonStriker} onChange={setNonStriker} players={players.filter(p=>p.id!==striker)}/><PlayerSelect label="Bowler" value={bowler} onChange={setBowler} players={fielding.players.filter(p=>!innings?.needsBowler||p.id!==innings.previousBowler)}/><button disabled={busy||striker===nonStriker} className="button primary full">{innings?'Apply correction':'Start innings'}</button></form></Modal>;
}
function RetireDialog({config:c,innings:i,busy,onClose,onSubmit}:{config:Config;innings:Innings;busy:boolean;onClose:()=>void;onSubmit:(p:string,n:string,o:boolean)=>void}){
 const [player,setPlayer]=useState(i.striker),[incoming,setIncoming]=useState(''),[out,setOut]=useState(false);
 return <Modal title="Retire a batter" onClose={onClose}><form className="dialog-form" onSubmit={e=>{e.preventDefault();if(confirm(`${out?'Retired out (counts as a wicket)':'Retired hurt (no wicket)'} for ${playerName(c,player)}?`))onSubmit(player,incoming,out);}}><PlayerSelect label="Who is leaving the field?" value={player} onChange={setPlayer} players={[i.striker,i.nonStriker].map(id=>({id,name:playerName(c,id)}))}/><label>Reason<select value={out?'out':'hurt'} onChange={e=>setOut(e.target.value==='out')}><option value="hurt">Retired hurt · no wicket</option><option value="out">Retired out · counts as a wicket</option></select></label><PlayerSelect label="Who is coming in?" value={incoming} onChange={setIncoming} players={Object.values(i.batters).filter(b=>['Yet to bat','Retired hurt'].includes(b.status)).map(b=>({id:b.id,name:playerName(c,b.id)}))}/><p className="muted">A retired-hurt batter can return later. Retired out does not give the bowler a wicket.</p><button disabled={busy} className="button primary full">Record retirement</button></form></Modal>;
}
function DeliveryDialog({config:c,innings:i,mode,initial,busy,onClose,onSubmit}:{config:Config;innings:Innings;mode:string;initial?:Ball;busy:boolean;onClose:()=>void;onSubmit:(b:Ball)=>Promise<boolean>}){
 const [extra,setExtra]=useState<Ball['extra']>(initial?.extra??(mode==='wide'?'wide':mode==='no-ball'?'no-ball':mode==='extras'?'bye':mode==='leg-bye'?'leg-bye':'none')),[bat,setBat]=useState(initial?.bat??0),[extraRuns,setExtraRuns]=useState(initial?.extraRuns??(mode==='wicket'||mode==='edit'?0:1)),[additional,setAdditional]=useState<'bat'|'bye'|'leg-bye'>(initial?.noBallAdditional??'bat');
 const [wicket,setWicket]=useState(!!initial?.wicket||mode==='wicket'),[player,setPlayer]=useState(initial?.wicket?.player??i.striker),[how,setHow]=useState<NonNullable<Ball['wicket']>['how']>(initial?.wicket?.how??'Bowled'),[incoming,setIncoming]=useState(initial?.wicket?.incoming??''),[fielder,setFielder]=useState(initial?.wicket?.fielder??''),[nextStriker,setNextStriker]=useState(initial?.wicket?.nextStriker??''),[boundary,setBoundary]=useState(initial?.boundary!==false),[error,setError]=useState('');
 const available=Object.values(i.batters).filter(b=>['Yet to bat','Retired hurt'].includes(b.status)).map(b=>({id:b.id,name:playerName(c,b.id)}));
 const needIncoming=i.wickets+1<i.wicketLimit && (i.balls+(extra==='wide'||extra==='no-ball'?0:1))<i.limit;
 const changeExtra=(v:Ball['extra'])=>{setExtra(v);setBat(0);setExtraRuns(v==='none'?0:1);};
 return <Modal title={mode==='edit'?'Correct this delivery':mode==='wicket'?'Record a wicket':mode==='wide'?'How many wides?':mode==='no-ball'?'Record a no-ball':'Byes & leg byes'} onClose={onClose}><form className="dialog-form" onSubmit={async e=>{e.preventDefault();setError('');const b:Ball={kind:'ball',...(initial?{id:initial.id,at:initial.at}:stamp()),bat,extra,extraRuns,noBallAdditional:extra==='no-ball'?additional:undefined,boundary,wicket:wicket?{player,how,incoming:incoming||undefined,fielder:fielder||undefined,nextStriker:nextStriker||undefined}:undefined};try{const ok=await onSubmit(b);if(!ok)setError('Not saved. Check the validation message on the scorer page.');}catch(e){setError((e as Error).message);}}}>
 {(mode==='edit'||mode==='wicket')&&<label>Delivery type<select value={extra} onChange={e=>changeExtra(e.target.value as Ball['extra'])}><option value="none">Normal ball</option><option value="wide">Wide</option><option value="no-ball">No-ball</option><option value="bye">Byes</option><option value="leg-bye">Leg byes</option></select></label>}
 {(mode==='extras'||mode==='leg-bye')&&<div className="choice-row">{(['bye','leg-bye'] as const).map(v=><button type="button" className={extra===v?'selected':''} key={v} onClick={()=>changeExtra(v)}>{v==='bye'?'Byes':'Leg byes'}</button>)}</div>}
 {extra==='no-ball'&&<><p className="notice">1 penalty run is included. This does not count as a legal ball.</p><label>Additional runs<select value={additional} onChange={e=>{setAdditional(e.target.value as typeof additional);setBat(0);setExtraRuns(1);}}><option value="bat">Off the bat</option><option value="bye">Byes</option><option value="leg-bye">Leg byes</option></select></label></>}
 {(extra==='none'||extra==='no-ball'&&additional==='bat')&&<label>{wicket?'Completed runs off the bat':'Runs off the bat'}<RunPicker value={bat} onChange={setBat} values={[0,1,2,3,4,5,6]}/></label>}
 {extra!=='none'&&!(extra==='no-ball'&&additional==='bat')&&<label>{extra==='wide'?'Total wides (includes the penalty)':extra==='no-ball'?'Additional byes / leg byes':'Runs completed'}<RunPicker value={extra==='no-ball'?extraRuns-1:extraRuns} onChange={v=>setExtraRuns(extra==='no-ball'?v+1:v)} values={extra==='no-ball'?[0,1,2,3,4,5]:[1,2,3,4,5,6]}/></label>}
 {(bat===4||bat===6)&&<label className="checkbox"><input type="checkbox" checked={boundary} onChange={e=>setBoundary(e.target.checked)}/>Boundary (untick if all runs were run)</label>}
 {mode==='edit'&&<label className="checkbox"><input type="checkbox" checked={wicket} onChange={e=>setWicket(e.target.checked)}/>A wicket fell</label>}
 {wicket&&<><PlayerSelect label="1. Who is out?" value={player} onChange={setPlayer} players={[i.striker,i.nonStriker].map(id=>({id,name:playerName(c,id)}))}/><label>2. How were they out?<select value={how} onChange={e=>setHow(e.target.value as typeof how)}>{dismissalSchema.options.map(h=><option key={h}>{h}</option>)}</select></label>{how==='Other'&&<p className="notice">Use only for an umpire-confirmed dismissal such as obstructing the field. No bowler wicket is credited.</p>}{how==='Run out'&&<p className="notice">Enter only completed runs above. The unfinished run does not count.</p>}{needIncoming&&<PlayerSelect label="3. Who is the new batter?" value={incoming} onChange={setIncoming} players={available}/>}<details><summary>Optional: fielder & run-out ends</summary><label>Fielder<select value={fielder} onChange={e=>setFielder(e.target.value)}><option value="">Not recorded</option>{c.teams.find(t=>t.id===i.fielding)!.players.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{how==='Run out'&&<label>Batter at the striker’s end after the run-out<select value={nextStriker} onChange={e=>setNextStriker(e.target.value)}><option value="">Automatic (based on completed runs)</option>{[i.striker,i.nonStriker,incoming].filter(id=>id&&id!==player).map(id=><option key={id} value={id}>{playerName(c,id)}</option>)}</select><small>Before the automatic end-of-over swap. Ask the umpire if the batters crossed during the unfinished run.</small></label>}</details></>}
 {error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="button primary full">{busy?'Saving…':`Record ${wicket?'wicket':`${bat+extraRuns} run${bat+extraRuns===1?'':'s'}`}`}</button></form></Modal>;
}
function RunPicker({value,onChange,values}:{value:number;onChange:(v:number)=>void;values:number[]}){return <div className="run-picker">{values.map(v=><button type="button" key={v} className={value===v?'selected':''} onClick={()=>onChange(v)}>{v}</button>)}</div>;}
